### ISSUE TITLE
qlooctl doesn't return schema from petstore example

### ISSUE THREAD

**Issue by CamelCaseNotation** [solo-io/qloo#3]
```
# The query type, represents all of the entry points into our object graph
type Query {
    pets: [Pet]
    pet(id: Int!): Pet
}

type Mutation {
    addPet(pet: InputPet!): Pet
}

type Pet{
    id: ID!
    name: String!
    status: Status!
}

input InputPet{
    id: ID!
    name: String!
    tag: String
}

enum Status {
    pending
    available
}
```
I put the above schema into a file called `petstore.graphql` then uploaded it via qlooctl as per the petstore k8s example.
```
> qlooctl schema create petstore -f ./petstore.graphql
> qlooctl schema get petstore
petstore%
```

What I expected was to see the schema I had just uploaded. I also tried uploading the schema in the manner the help text of `qlooctl` described:
`qlooctl schema create petstore --from-file ./petstore.graphql`

Same error

**Comment by CamelCaseNotation** [comment]
I also tried creating the schema in the way it's created in `demo.sh` of the petstore dir:
`qlooctl schema create -f ./petstore.graphql petstore`

That also yielded same error

**Comment by CamelCaseNotation** [comment]
Specifying `-o yaml` gives expected results:
```
> qlooctl schema get petstore -o yaml
inline_schema: |
  # The query type, represents all of the entry points into our object graph
  type Query {
      pets: [Pet]
      pet(id: Int!): Pet
  }

  type Mutation {
      addPet(pet: InputPet!): Pet
  }

  type Pet{
      id: ID!
      name: String!
      status: Status!
  }

  input InputPet{
      id: ID!
      name: String!
      tag: String
  }

  enum Status {
      pending
      available
  }
metadata:
  namespace: gloo-system
  resource_version: "2353949"
name: petstore
resolver_map: petstore-resolvers
status:
  state: Accepted
```

**Comment by ilackarms** [comment]
does this mean the issue is resolved? I don't see that you posted any error

**Comment by CamelCaseNotation** [comment]
I closed the issue because I was interpreting the default behavior as an error. The "error" was that I expected the schema to print out whereas I just got the name of the schema

**Comment by ilackarms** [comment]
`qlooctl ... -o yaml` will print the content of the schema
